from fastapi import HTTPException
from sqlmodel import Session, select

from app.models import Todo, TodoCreate


def get_todos(session: Session):
    statement = select(Todo)
    todos = session.exec(statement).all()
    return todos


def create_todo(session: Session, todo_data: TodoCreate):
    todo = Todo.model_validate(todo_data)
    try:
        session.add(todo)
        # Add the `Todo` instance to the database
        session.add(todo)
        session.commit()

        # to ensure object has latest information from autogenerated id field
        session.refresh(todo)
        return todo

    except Exception as e:
        # Handle the exception
        session.rollback()
        raise HTTPException(status_code=400, detail=f"Error creating todo: {str(e)}")
